{{- include "_config.load" $ }}
{{- if .Values.features.eirini.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opi
  namespace: {{ .Release.Namespace }}
{{- if gt (len .Values.kube.image_pull_secrets) 0 }}
imagePullSecrets:
  {{- range $secret_name := $.Values.kube.image_pull_secrets }}
  - name: "{{ $secret_name }}"
  {{- end }}
{{- end }}
{{- end }}
